/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorldRouteImport } from './routes/_authenticated/world'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedFarmRouteImport } from './routes/_authenticated/farm'
import { Route as AuthenticatedCodexRouteImport } from './routes/_authenticated/codex'
import { Route as AuthenticatedBreedRouteImport } from './routes/_authenticated/breed'
import { Route as AuthenticatedArenaRouteImport } from './routes/_authenticated/arena'
import { Route as AuthenticatedWorldForestRouteImport } from './routes/_authenticated/world.forest'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorldRoute = AuthenticatedWorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFarmRoute = AuthenticatedFarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCodexRoute = AuthenticatedCodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBreedRoute = AuthenticatedBreedRouteImport.update({
  id: '/breed',
  path: '/breed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArenaRoute = AuthenticatedArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorldForestRoute =
  AuthenticatedWorldForestRouteImport.update({
    id: '/forest',
    path: '/forest',
    getParentRoute: () => AuthenticatedWorldRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arena': typeof AuthenticatedArenaRoute
  '/breed': typeof AuthenticatedBreedRoute
  '/codex': typeof AuthenticatedCodexRoute
  '/farm': typeof AuthenticatedFarmRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/world': typeof AuthenticatedWorldRouteWithChildren
  '/world/forest': typeof AuthenticatedWorldForestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arena': typeof AuthenticatedArenaRoute
  '/breed': typeof AuthenticatedBreedRoute
  '/codex': typeof AuthenticatedCodexRoute
  '/farm': typeof AuthenticatedFarmRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/world': typeof AuthenticatedWorldRouteWithChildren
  '/world/forest': typeof AuthenticatedWorldForestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/arena': typeof AuthenticatedArenaRoute
  '/_authenticated/breed': typeof AuthenticatedBreedRoute
  '/_authenticated/codex': typeof AuthenticatedCodexRoute
  '/_authenticated/farm': typeof AuthenticatedFarmRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/world': typeof AuthenticatedWorldRouteWithChildren
  '/_authenticated/world/forest': typeof AuthenticatedWorldForestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arena'
    | '/breed'
    | '/codex'
    | '/farm'
    | '/leaderboard'
    | '/marketplace'
    | '/world'
    | '/world/forest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arena'
    | '/breed'
    | '/codex'
    | '/farm'
    | '/leaderboard'
    | '/marketplace'
    | '/world'
    | '/world/forest'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/arena'
    | '/_authenticated/breed'
    | '/_authenticated/codex'
    | '/_authenticated/farm'
    | '/_authenticated/leaderboard'
    | '/_authenticated/marketplace'
    | '/_authenticated/world'
    | '/_authenticated/world/forest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/world': {
      id: '/_authenticated/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof AuthenticatedWorldRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/farm': {
      id: '/_authenticated/farm'
      path: '/farm'
      fullPath: '/farm'
      preLoaderRoute: typeof AuthenticatedFarmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/codex': {
      id: '/_authenticated/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof AuthenticatedCodexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/breed': {
      id: '/_authenticated/breed'
      path: '/breed'
      fullPath: '/breed'
      preLoaderRoute: typeof AuthenticatedBreedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/arena': {
      id: '/_authenticated/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof AuthenticatedArenaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/world/forest': {
      id: '/_authenticated/world/forest'
      path: '/forest'
      fullPath: '/world/forest'
      preLoaderRoute: typeof AuthenticatedWorldForestRouteImport
      parentRoute: typeof AuthenticatedWorldRoute
    }
  }
}

interface AuthenticatedWorldRouteChildren {
  AuthenticatedWorldForestRoute: typeof AuthenticatedWorldForestRoute
}

const AuthenticatedWorldRouteChildren: AuthenticatedWorldRouteChildren = {
  AuthenticatedWorldForestRoute: AuthenticatedWorldForestRoute,
}

const AuthenticatedWorldRouteWithChildren =
  AuthenticatedWorldRoute._addFileChildren(AuthenticatedWorldRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedArenaRoute: typeof AuthenticatedArenaRoute
  AuthenticatedBreedRoute: typeof AuthenticatedBreedRoute
  AuthenticatedCodexRoute: typeof AuthenticatedCodexRoute
  AuthenticatedFarmRoute: typeof AuthenticatedFarmRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedWorldRoute: typeof AuthenticatedWorldRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedArenaRoute: AuthenticatedArenaRoute,
  AuthenticatedBreedRoute: AuthenticatedBreedRoute,
  AuthenticatedCodexRoute: AuthenticatedCodexRoute,
  AuthenticatedFarmRoute: AuthenticatedFarmRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedWorldRoute: AuthenticatedWorldRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
